stages:
    - quality
    - build

.go-cache:
    variables:
        GOPATH: $CI_PROJECT_DIR/.go
    cache:
      paths:
        - .go/pkg/mod/

api_lint:
  stage: quality
  image: golangci/golangci-lint
  script:
    - cd api
    - golangci-lint run -v --color=always

api_unit_tests:
    stage: quality
    image: golang
    script:
        - cd api
        - go test -v -race ./... -coverprofile .goCoverage.txt

api_build:
    stage: build
    image: golang
    script:
        - cd api
        - env GOOS=linux GOARCH=amd64 go build -o output-amd64
        - env GOOS=linux GOARCH=arm GOARM=7 go build -o output-pi3
    artifacts:
        paths:
            - api/output-amd64
            - api/output-pi3
