stages:
    - test
    - build

cache:
    paths:
        - /$GOPATH/src/github.com
        - /$GOPATH/src/golang.org
        - /$GOPATH/src/gopkg.in

api_unit_tests:
    stage: test
    image: golang
    before_script:
        - mkdir -p $GOPATH/src/$REPO/$GROUP $GOPATH/src/_/builds
        - cp -r $CI_PROJECT_DIR $GOPATH/src/$REPO/$GROUP/$PROJECT
        - ln -s $GOPATH/src/$REPO/$GROUP $GOPATH/src/_/builds/$GROUP
        - go get -v -d -t ./...
    script:
        - go test -v ./api

api_build:
    stage: build
    image: golang
    before_script:
        - mkdir -p $GOPATH/src/$REPO/$GROUP $GOPATH/src/_/builds
        - cp -r $CI_PROJECT_DIR $GOPATH/src/$REPO/$GROUP/$PROJECT
        - ln -s $GOPATH/src/$REPO/$GROUP $GOPATH/src/_/builds/$GROUP
        - go get -v -d ./...
        - ls
    script:
        - cd api
        - env GOOS=linux GOARCH=amd64 go build -o output-amd64
        - env GOOS=linux GOARCH=arm GOARM=7 go build -o output-pi3
    artifacts:
        paths:
            - api/output-amd64
            - api/output-pi3
