server:
    port: 7344
    signingkey: "mySuperSecretPhrase"

database:
    location: "tea-store.db"
    teaTypes:
        - "Black Tea"
        - "Chai Tea"
        - "Chinese Tea"
        - "Fruit Tea"
        - "Green Tea"
        - "Herbal Tea"
        - "Matcha"
        - "Mint Tea"
        - "Rooibos"
        - "White Tea"
    owners:
        - "Brad"
        - "Kine"
        - "Sam"
